### ISSUE TITLE
No LICENSE file, license mentioned in the Readme, or license field in the gemspec

### ISSUE THREAD

**Issue by nathantalewis** [shakacode/cypress-on-rails#12]
Please add a mention somewhere of how this gem is licensed.

**Comment by yagudaev** [comment]
@grantspeelman can you please add an MIT license to the gem?

If you don't have a license mentioned it means the original author owns all the rights and we cannot modify it and help contribute.

MIT is the simplest and most versatile license there is and always a good sign when you see it on an OSS project.

**Comment by grantspeelman** [comment]
Guess I should of checked this as well before modifying @derfred 's code :)
