### ISSUE TITLE
gem emits deprecation warning on its own, when configured properly

### ISSUE THREAD

**Issue by bmulholland** [shakacode/cypress-on-rails#135]
When performing any command, it loads the e2e helper, which does:

https://github.com/shakacode/cypress-on-rails/blob/f7132135b3c761063f82e0ce8d8938e2be0838a6/lib/cypress_on_rails/command_executor.rb#L18

which calls

https://github.com/shakacode/cypress-on-rails/blob/f7132135b3c761063f82e0ce8d8938e2be0838a6/lib/cypress_on_rails/configuration.rb#L13

So it always emits "cypress_folder is deprecated, please use install_folder" when used

**Comment by grantspeelman** [comment]
thanks @bmulholland , this has been fixed in #136
