### ISSUE TITLE
Rails 7.1 Content-Type Issue: "An empty string is not a valid JSON string."

### ISSUE THREAD

**Issue by jtannas** [shakacode/cypress-on-rails#141]
Heyo - thanks for the helpful gem :bow: 

We just ran into the following set of errors when upgrading from Rails 7.0 to Rails 7.1

<details>
<summary>Screenshots</summary>

![image](https://github.com/shakacode/cypress-on-rails/assets/22785056/7554eab6-35a4-4ce0-bd7d-2330fc568c7d)

![image](https://github.com/shakacode/cypress-on-rails/assets/22785056/dfb5d3d6-ec68-4f69-a4f1-8bb3aa02d747)
</details>

Turns out `JSON.parse(req.body.read)` was returning an empty string because the `content-type` header wasn't set in the cypress request.
We managed to fix it on the client side by adding the content type header to the `appCommands`
![image](https://github.com/shakacode/cypress-on-rails/assets/22785056/366e8ac4-74a8-4ba1-b7fa-9b5f2c239c5a)

The other way that we could get it to work was replacing `JSON.parse(req.body.read)` with `JSON.parse(req.body)` in the middleware, but decided against it because it required overriding the gem code.

https://github.com/shakacode/cypress-on-rails/blob/c36e2862a89ab117560701660f90365c08e9bfd2/lib/cypress_on_rails/middleware.rb#L54

Might be worth updating the `on-rails.js` template to include the content type header.

**Comment by nijikon** [comment]
This fixes it for me as well. Thanks @jtannas 💜
