### ISSUE TITLE
Scenario Variables

### ISSUE THREAD

**Issue by ericraio** [shakacode/cypress-on-rails#15]
My application uses Faker and randomly generates new values for FactoryBot.

I currently have a Scenario that does some fresh setup, Is there a way to define a variable here and access it in the tests?

**Comment by grantspeelman** [comment]
@ericraio can you give an example of what a test would look like?

setting and using variables goes against the grain with Cypress. Cypress kinda expects you to be in control of the data. It might make sense to rather set the values that you care about in the test for example:
```
cy.appFactories([
  ["create", "person", {first_name: "Jeff"}]  // set first name to be used later in the test
])
cy.visit("/people")
cy.contains("Jeff")
```

Additional Reading: https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Return-Values

**Comment by ericraio** [comment]
@grantspeelman Thanks for the reply! This makes sense.

I have a multi tenant app that has a lot of setup first before the test can execute, I encapsulated all of this into an app scenario.

However,

Given that I set the values for all the data I care about, I would still need to pass the ID from one factory  to the other factory to have everything be associated properly.

Any suggestions?

**Comment by grantspeelman** [comment]
you could use the `cy.app` and pass additional information to your scenarios

Example:

in cypress test
```js
  cy.app('scenarios/big_setup', {user_email: 'my@mail.com'})
  cy.visit("/people")
  cy.contains("my@mail.com")
```

in cypress/scenarios/big_setup.rb
```rb
  factory =  CypressDev::SmartFactoryWrapper
  user = factory.create(:user, command_options.fetch('user_email'))
  profile = factory.create(:profile, user: user)
  # more linking of stuff here
  # etc
```

Will this work for you?

**Comment by ericraio** [comment]
@grantspeelman This would work great!

We could update the appScenario to something like this. Would this make sense in the generator?

```js
 Cypress.Commands.add('appScenario', (name, options = {}) => {
  cy.app('scenarios/' + name, options)
});
```

**Comment by grantspeelman** [comment]
Yes, that makes sense 👍

**Comment by bphelps16** [comment]
@grantspeelman @ericraio Is this solution still relevant? I am trying to implement this in my app, but am getting an error that `command_options` is nil: `message: "undefined method `fetch' for nil:NilClass", class: 'NoMethodError'`. In looking at the code, it doesn't look like the `command_options` variable is being returned anywhere, so I'm not sure if that has changed since this post.

**Comment by grantspeelman** [comment]
@bphelps16 You error message looks like a ruby error. Can't tell exactly what is wrong from that. Can you give more context? 
Like what the cypress code looks like and what the factory looks like.

**Comment by bphelps16** [comment]
Hi @grantspeelman! Yeah, so my `spec` file looks something like this
```
cy.appScenario('user_can_load_portal', {
      login: 'some_login',
      password: 'some_password'
    });
```
the `user_can_load_portal` scenario looks like this
```
 factory =  CypressDev::SmartFactoryWrapper
 user = factory.create(:user, login: command_options.fetch('login'), password: command_options.fetch('password')
```

The system seems to error out on `command_options.fetch` as it's returning `nil` for `command_options`

**Comment by grantspeelman** [comment]
@bphelps16 hmmmm 🤔 

Can you also share what the `appScenario` command looks in `cypress/support/on-rails.js` and what version of `cypress-on-rails` you are using please.

**Comment by bphelps16** [comment]
@grantspeelman Thats the problem! I had added the below to `commands.js`
```
Cypress.Commands.add('appScenario', (name, options = {}) => {
  cy.app('scenarios/' + name, options)
});
```
but I think i need to change our `on-rails.js` because currently it looks like this
```
Cypress.Commands.add('appScenario', function (name) {
  cy.app('scenarios/' + name)
});
```

`cypress-on-rails` version `cypress-on-rails (1.12.1)` btw
