### ISSUE TITLE
Webpack Configuration for components testing

### ISSUE THREAD

**Issue by sap1enza** [shakacode/cypress-on-rails#156]
Hello,

I'm new to cypress and I'm studying to implement it in my company. Ideally we would have the ability to test E2E and components
E2E tests are working like a charm, the problem is setting up the components with webpacker.

Didn't find any solution or similar case here or in the issues, neither the cypress documentation worked.

I've configured the cypress folder to be within `spec/cypress`

<img width="913" alt="image" src="https://github.com/shakacode/cypress-on-rails/assets/27630941/1892cc0c-98c1-40ab-ab3b-840736a8655d">

Thanks!

**Comment by grantspeelman** [comment]
sorry, out of scope for the project.

I suggest following the cypress documentation on component tests : https://docs.cypress.io/guides/component-testing/overview
