### ISSUE TITLE
Is it possible for scenarios to return a response?

### ISSUE THREAD

**Issue by benlieb** [shakacode/cypress-on-rails#158]
I would like to get data back from my scenarios, something like

```js
cy.appScenario('basic').then((scenarioData) => {
  cy...
});
```

Is this possible?

**Comment by grantspeelman** [comment]
yes, just put what you want to return as the last thing in the scenario file and make sure it 's something that can be converted to JSON

**Comment by benlieb** [comment]
Interesting. I'll test and report back. Would a PR be accepted if I added this to the documentation?

**Comment by benlieb** [comment]
Yep worked

**Comment by grantspeelman** [comment]
awesome
