### ISSUE TITLE
Include Devise test helpers

### ISSUE THREAD

**Issue by eamon-clixifix** [shakacode/cypress-on-rails#16]
Hello,

I am trying to include the Devise Test helpers so I can login programmatically.
I have added the following code in app_commands/scenarios/my_scenario.rb

```
require 'factory_bot'
include Devise::Test::IntegrationHelpers
user = FactoryBot.create(:user, :test_user)
sign_in user
```

The user is generated fine, but it fails with an error:

```
unexpected error while processing request: undefined method `setup' for CypressDev::CommandExecutor:Class
	/Users/eamon/.rvm/gems/ruby-2.5.5/gems/cypress-on-rails-1.3.0/lib/cypress_dev/command_executor.rb:9:in `eval'
	/Users/eamon/.rvm/gems/ruby-2.5.5/gems/devise-4.6.1/lib/devise/test/integration_helpers.rb:23:in `class_eval'
	/Users/eamon/.rvm/gems/ruby-2.5.5/gems/devise-4.6.1/lib/devise/test/integration_helpers.rb:23:in `included'
```
It seems to be because it is not within a class, which I don't have in this case, and even trying to wrap it in one doesn't work .
Has anyone been able to get this to work?

Many thanks

Eamon

**Comment by grantspeelman** [comment]
hmmmm, unfortunately you not able to use `Devise::Test::IntegrationHelpers` as you don't have access to the request, cookies or sessions object which is something that i should add at some point.

As a work around here is what I currently use to login in user.

in routes.rb
```rb
Rails.application.routes.draw do
  # ...... you other routs
  unless Rails.env.production?
    scope path: "/__cypress__", controller: 'cypress' do
      post "forceLogin", action: 'force_login'
    end
  end
end
```

app/controllers/cypress_controller.rb
```rb
class CypressController < ApplicationController
  skip_before_action :verify_authenticity_token

  def force_login
    if params[:email].present?
      user = User.find_by!(email: params.require(:email))
    else
      user = User.first!
    end
    sign_in(user)
    redirect_to URI.parse(params.require(:redirect_to)).path
  end
end
```

in cypress/support/on-rails.js
```js
Cypress.Commands.add("forceLogin", (details) => {
  if(!details)
    details = {}

  if(!details.redirect_to)
    details.redirect_to = '/'

  cy.visit("__cypress__/forceLogin",
    { method: "POST", body: { email: details.email, redirect_to: details.path }  })
});
```

examples of usage in cypress specs
```js
cy.forceLogin()
cy.forceLogin({redirect_to: '/profile'})
cy.forceLogin({email: 'someuser@mail.com'})
```

Let me know if this helps you

**Comment by eamon-clixifix** [comment]
Thank you, I will give it a try and let you know

**Comment by justin808** [comment]
I added this as our first doc file:

https://github.com/shakacode/cypress-on-rails/blob/master/docs/authentication.md

**Comment by alexsligar** [comment]
If I want to login to a rails app that uses devise using cy.request(), is this the only method? I've successfully been able to login via the web form and then access protected views, but not with cy.request. I followed the recipe on Cypress for using cy.request() and can see that the session_id is set. However, when I attempt to access a protected page, I am redirected to the login page. I am assuming that there is something I don't understand about Devise/Warden that prevents this from working without using the above work-around.

**Comment by grantspeelman** [comment]
@alexsligar if you could post example of how your test looks or an example repo of the problem, that could possible help us figure out what is wrong. Unfortunately not able to deduce what the issue could be from the information you have given.

**Comment by alexsligar** [comment]
I am using a Cypress command:
```
Cypress.Commands.add("login", () => {
    return cy.request({
        method: 'POST',
        url: '/d/users/sign_in',
        form: true,
        body: {
            'user["email"]': "test@domain.com",
            'user["password"]': "Test@123"
        }
    })
})
```

Then in my test, I run something like this:

```
    beforeEach(() => {
        cy.app('clean')
        cy.login()
    })

    afterEach(() => {
        cy.app('finish_clean')
    })

    it('name should be required', function() {
        cy.appScenario('building')
        cy.visit('/buildings/1/edit')
    })
```
It successfully calls cy.login() and I can test that the session_id cookie is set. However, it gets redirected to the login page whenever I attempt to visit /building/1/edit. If I instead write the following for my login command, I am not redirected and can access /building/1/edit:

```
Cypress.Commands.add("login", () => {
    cy.visit('/')
    cy.get('[name="user[email]"').type('test@domain.com')
    cy.get('[name="user[password]"').type('Test@123')
    cy.get('#login_button').click()
})
```

**Comment by alexsligar** [comment]
Also, I was able to use the forceLogin() command suggested above and not get redirected. However, I was hoping to avoid adding this into the code base and use cy.request() to login via Devise.

**Comment by grantspeelman** [comment]
@alexsligar I see, the most likely issue is rails wanting the "authenticity_token". In the cypress controller above you will see `skip_before_action :verify_authenticity_token`

You can set failOnStatusCode to "true" on cypress requests, which will fail the cypress test if the request does not return a success status.

```js
Cypress.Commands.add("login", () => {
    return cy.request({
        method: 'POST',
        url: '/d/users/sign_in',
        form: true,
        failOnStatusCode: true,
        body: {
            'user["email"]': "test@domain.com",
            'user["password"]': "Test@123"
        }
    })
})
```

**Comment by alexsligar** [comment]
@grantspeelman interestingly, it does not fail. This command returns a 200 status and the _session_id cookie is set. However, it still 302 redirects to /d/users/sign_in upon visiting another page. I can even check for the presence of the _session_id cookie prior to attempting to visit another page and I see it is set.

**Comment by grantspeelman** [comment]
@alexsligar from my understanding you always get a session cookie any time you interact with rails, even when you are not logged in. Hmmm, I am not sure to be honest. Why is there a `d` in your url?

```js
    cy.request({
      method: 'POST',
      url: '/accounts/sign_in',
      form: true,
      failOnStatusCode: true,
      body: {
        'account["email"]': "fred@flintstone.com",
        'account["password"]': "Pass1234"
      }
    })
```
Doing the above against our codebase gives a 422 response, which is related to the `authenticity_token`.

**Comment by corwinstephen** [comment]
> @grantspeelman interestingly, it does not fail. This command returns a 200 status and the _session_id cookie is set. However, it still 302 redirects to /d/users/sign_in upon visiting another page. I can even check for the presence of the _session_id cookie prior to attempting to visit another page and I see it is set.

Also experiencing this. @alexsligar, did you ever figure this out?

**Comment by mapreal19** [comment]
@grantspeelman are you sure the login is successful? You can log the flash in an after_action filter to check if the login is working:

```ruby
after_action do
  puts flash.to_json
end
```

What I've found is that you're not sending the body correctly. `'user["email"]'` --> `'user[email]'`

Using this command with a Rails + Devise app I'm able to login and visit other pages:

```js
Cypress.Commands.add("login", user => {
  return cy.request({
    method: 'POST',
    url: "/users/sign_in",
    form: true,
    failOnStatusCode: true,
    body: {
      'user[email]': user.email,
      'user[password]': "password"
    }
  });
});
```

**Comment by grantspeelman** [comment]
good spot on the quotes inside the body params :+1:

**Comment by mapreal19** [comment]
@grantspeelman ;) I guess that this way should go into the docs. Less code and it's the recommended way for Cypress:

https://docs.cypress.io/guides/getting-started/testing-your-app.html#Bypassing-your-UI

cc @justin808
