### ISSUE TITLE
Ruby 3.2 compatibility

### ISSUE THREAD

**Issue by hmdros** [shakacode/cypress-on-rails#162]
Hello!
Using `cypress-on-rails` ~> `1.8.0` and upgrading Ruby version to `3.3.0`.
The situation is: Ruby 3.2.0 **removed** `File.exists?` and `Dir.exists?` deprecated methods [here](https://github.com/ruby/ruby/pull/5352).
This change was later addressed by [cypress-on-rails](https://github.com/shakacode/cypress-on-rails/pull/95) in version `1.12.0`.

We need to either update the `gemspec` to have this requirement in older versions, or move the fix to older versions.
I would also suggest to update the `CHANGELOG.md` to have flags for compatibility and breaking changes.

I would be happy to open PRs with the solution you want. 😄

**Comment by grantspeelman** [comment]
We really only support one version track and don't backport any fixes to earlier versions.
We are however open to PRs that backports fixes to earlier versions 👍🏽
