### ISSUE TITLE
Issue with suggested port 5002

### ISSUE THREAD

**Issue by spaghetticode** [shakacode/cypress-on-rails#20]
TL;DR: I'm having issues in using the suggested port in the examples `5002`, so it may make sense changing the port number to a less used one.

I'm on OSX, and if I `curl -I localhost:5002` I get
```
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache, no-store, must-revalidate
Date: Thu, 20 Jun 2019 09:21:47 GMT
Content-Length: 23
Content-Type: text/plain; charset=utf-8
```
It seems there's some service already running on that port:
```
$ lsof -i TCP:5002
COMMAND   PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
agent   10172 andrea   11u  IPv4 0x4b127be231ef2135      0t0  TCP localhost:rfe (LISTEN)
```

Doing a google search, port 5002 seems to be related to `radio free ethernet`, and this is documented in the [IANA port list](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=5002):

```
rfe                5002        tcp    radio free ethernet
rfe                5002        udp    radio free ethernet
```

**Comment by justin808** [comment]
Any suggested port? We're open to a PR to change the default. This is where the default is set:

https://github.com/shakacode/cypress-on-rails/blob/49f1f7b2a912a15142baf137b0ea31a0378c9e92/lib/generators/cypress_on_rails/templates/spec/cypress.json#L2

```
{
  "baseUrl": "http://localhost:5002",
  "defaultCommandTimeout": 10000
}
```

**Comment by spaghetticode** [comment]
According to [this list](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt) there are a few ranges of ports that are not assigned, the closest to the current setting is `5016-5019`, and this [wikipedia page](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers) seems to confirm it.
