### ISSUE TITLE
Serialize and return created factories in response body

### ISSUE THREAD

**Issue by josephan** [shakacode/cypress-on-rails#23]
Would it be useful to render the json of the create factory/factories so it can be accessed in the test?
```javascript
cy.appFactories([
  ['create', 'user']
]).then(($response) => {
  const user = $response.body;

  cy.visit('/login')
    .get('#login-email')
    .type(user.email)
})

```
Currently the `$response.body` value above is just `"success"`:
```json
{
  "body": "success",
  "headers": {  },
  "status": 201,
  "statusText": "Created",
  "isOkStatusCode": true,
  "requestHeaders": {  },
  "requestBody": "{\"name\":\"factory_bot\",\"options\":[[\"create\",\"user\"]]}",
  "duration": 344,
  "...": "..."
}
```

If you guys are open to this change I can implement this.

**Comment by Doctor06** [comment]
@josephan I would love this. How are you planning on implementing this?
Middle ware is sending the success now. We can change it in there and pass the returned factories just created.

**Comment by grantspeelman** [comment]
Yes open to this change, could be very useful 👍 

We might have to modify the use case just a bit as appFactories takes a list, so the response will be a list

```js
  const user = $response.body[0];
```

**Comment by Doctor06** [comment]
I overwrote the handle_command in middleware.rb to return json and it worked for me.

```javascript
def handle_command(req)
  body = JSON.parse(req.body.read)
  logger.info "handle_command: #{body}"
  commands = Command.from_body(body, configuration)
  missing_command = commands.find {|command| !@file.exists?(command.file_path) }
  if missing_command.nil?
    factories = commands.map { |command| @command_executor.load(command.file_path, command.options) }
    [201, {}, [Hash[factories.flatten.each_with_index.map { |value, index| [index, value] }].to_json]]
  else
    [404, {}, ["could not find command file: #{missing_command.file_path}"]]
  end
end

**Comment by justin808** [comment]
@josephan If you create a PR, we'll review it ASAP. 😄

**Comment by ro-savage** [comment]
Just started using cypress on rails. And not being able to get the data retuned from our factories is making this quite limiting. Would love to see this feature added.

**Comment by grantspeelman** [comment]
Released a [new version](https://rubygems.org/gems/cypress-on-rails/versions/1.5.0) of cypress on rails that allows you to do this.

It will require updating the cypress support files by running the update generator.
```bash
bin/rails g cypress_on_rails:update --cypress_folder=spec/cypress
```

Then you should be able to do code like this:
```js
cy.appFactories([['create', 'invoice', { paid: false }]]).then((records) => {  
  cy.visit(`/invoices/${records[0].id}`);
});
```

Thanks to @KevinMulhern for getting this going 👍
