### ISSUE TITLE
Consider solutions to reseting the database back to some prior state

### ISSUE THREAD

**Issue by justin808** [shakacode/cypress-on-rails#26]
Would it be useful if we could seed a database once and then reset it between tests using something like https://github.com/fastmonkeys/stellar?

or is https://github.com/DatabaseCleaner/database_cleaner sufficient for just about any use case?

@MUTOgen wrote:
> One particular thing i was thinking about is ability to partly reseting DB. For some cases it would speed up testing, b/c reseting and re-seeding sometimes look pretty heavy.

@grantspeelman wrote:

Can you elaborate more on the partly reseting of the DB? is this not something that database_cleaner already provides, ie so won't updating the clean.rb be enough?

Or are you thinking tighter integration with database_cleaner so you can specify it's options from within cypress.

For example
```js
cy.appCleanerStrategy('truncation', { only:  ["widgets", "dogs", "some_other_table"] })
cy.appCleanerClean()
```

**Comment by MUTOgen** [comment]
@justin808 @grantspeelman I played a little bit with one client project with Cypress on Rails setup.
Here are some thoughts:

1) For a quite big amount of fixtures, it might take about 10 seconds to load data. I tested it on ~60 `yml` files full of data. So, in case of big Cypress tests coverage, this might be a serious amount of time.

2) I like the idea of this tool https://github.com/fastmonkeys/stellar Nice thing about this is that it could apply in various projects. This is gonna be much faster for `beforeEach` hook. Bad thing is that it's an external tool in terms of project and code itself, just dumping tool.

3) DatabaseCleaner has one good strategy - `transaction`. It could be also considered to use. For example, we could fire `DatabaseCleaner.start` and `DatabaseCleaner.clean` on `beforeEach` and `afterEach` respectively. In this case, we don't need to worry about preparing data, it will roll back to the initial state automatically. Unfortunately, this approach has some [limitation](https://github.com/DatabaseCleaner/database_cleaner#supported-databases-libraries-and-strategies).

**Comment by gsouf** [comment]
@MUTOgen did you find a solution to be able to use transaction strategy with this gem?

**Comment by MUTOgen** [comment]
@gsouf Not really.
Actually, I use `truncation` strategy most of the time.
Do you have any reasons to do only `transaction`?

**Comment by gsouf** [comment]
@MUTOgen transaction is much faster for my use case. With rails test I use it to make everything faster.

It seems like that somehow [this other gem](https://github.com/testdouble/cypress-rails) has a way to do it using a "transactional server", not sure if it works well I have never tested

**Comment by grantspeelman** [comment]
hmmm, that is very interesting. I wonder how they manage to get a shared transaction scope across multiple connections.
I'll try and look into this at some point.

**Comment by bmulholland** [comment]
Very slow reply but here's how they do it: https://github.com/testdouble/cypress-rails/blob/67edef5c64fa50bec596262c6965b68e901133c7/lib/cypress-rails/manages_transactions.rb
