### ISSUE TITLE
how can i use simplecov gem with cypress-on-rails

### ISSUE THREAD

**Issue by badimalex** [shakacode/cypress-on-rails#28]
Hi friends.
Can somebody help me please.
It is good idea to initialize simplecov gem
https://github.com/colszowka/simplecov#getting-started
inside 
config/initializers/cypress_on_rails.rb
like this
```
if defined?(CypressOnRails)
  CypressOnRails.configure do |c|
    c.cypress_folder = File.expand_path("#{__dir__}/../../cypress")
    # WARNING!! CypressOnRails can execute arbitrary ruby code
    # please use with extra caution if enabling on hosted servers or starting your local server on 0.0.0.0
    c.use_middleware = Rails.env.test?
    c.logger = Rails.logger
  end
  require 'simplecov'
  SimpleCov.start 'rails'
end
```
Thanks for  help.

**Comment by olleolleolle** [comment]
The best way to do it is in the spec_helper (or equivalent test set-up file), as described in the simplecov documentation.

https://github.com/colszowka/simplecov#use-it-with-any-framework

It should not be started in an initializer, that would be "too late" for it to cover all you want to cover.

**Comment by olleolleolle** [comment]
The question in this Issue is perhaps best asked as a StackOverflow question.

**Comment by badimalex** [comment]
Thanks, i found answer
https://stackoverflow.com/a/10548281

```
# config/boot.rb
if ENV["SELENIUM"]
  require 'simplecov'
  SimpleCov.start 'rails'
end
```
