### ISSUE TITLE
FactoryBot 6.0 deprecation warnings

### ISSUE THREAD

**Issue by grantbdev** [shakacode/cypress-on-rails#37]
FactoryBot 5.1 [deprecated](https://github.com/thoughtbot/factory_bot/releases/tag/v5.1.0) `traits` and `sequences` methods and they are set to be removed in v6. `SmartFactoryWrapper`'s cleaning currently calls the deprecated methods: https://github.com/shakacode/cypress-on-rails/blob/8fc3cfae495f64ff8325aa69452b13e99cda981a/lib/cypress_on_rails/smart_factory_wrapper.rb#L8-L11

This is causing lots of deprecation warnings to be printed by the web server. I am not sure if this gem needs to continue calling the internal replacements or the calls can be removed instead.

**Comment by grantspeelman** [comment]
unfortunately we have to continue calling it because I sure there will be many projects that are still using traits and sequences, and we have to clear everything in order for reloading the factories changes to work effectively.

**Comment by grantspeelman** [comment]
is there a way to silence the warnings?

**Comment by grantbdev** [comment]
@grantspeelman I haven't had any luck disabling those warnings in particular and I don't want to disable all deprecation warnings.

Since the methods are being removed/moved in an upcoming version anyway, if this gem still needs to call them it may be worth having a conditional to call the new locations. I was hoping it would be as easy as passing `FactoryBot::Internal`, but that only responds to `factories`, `traits`, and `sequences` but not `callbacks`. It may be worth reaching out to the maintainers over there to see how they would handle the situation.

**Comment by vfonic** [comment]
One way to add a conditional could be to check if `FactoryBot` gem version is `< 6`:
https://stackoverflow.com/questions/2954279/how-do-you-check-the-gem-version-in-ruby-at-runtime

It doesn't seem like the cleanest solution though. I'm not sure what other gems do in this case.

**Comment by grantspeelman** [comment]
Any further discussion to be on #66
