### ISSUE TITLE
How to handle dependent factories

### ISSUE THREAD

**Issue by Zeouterlimits** [shakacode/cypress-on-rails#38]
Hey,

Thanks for creating and maintaining the library, is very cool to get to leverage existing rails system & tools for cypress.

My question / issue - how do I handle dependent factories? 
I have a factory for user for user and project, and am able to use them in ruby tests to create a user and then pass it to the project creation, but how do I do that in my cypress cy.appFactories?

Something like:
```
cy.appFactories([
      ['create', 'account' ],
      ['create', 'project', ':account' ]
    ])
```

Any help would be appreciated :)

**Comment by grantspeelman** [comment]
Maybe?

```js
cy.appFactories([['create', 'account' ]]).then((accounts) => {  
  cy.appFactories([
      ['create', 'project', { account_id: accounts[0].id }]
    ])
});
```

Or maybe just hardcode the ids.

```js
cy.appFactories([
  ['create', 'account', { id: 1 } ],
  ['create', 'project', { account_id: 1 } ]
 ])
```

**Comment by Zeouterlimits** [comment]
Think it has more to do with our factories, but yup, those would probably work in most cases, thanks.
