### ISSUE TITLE
Remote requests caching

### ISSUE THREAD

**Issue by dmitry** [shakacode/cypress-on-rails#39]
As a standard to prevent from fetching the data from the remote servers are used the libraries like VCR or puffing-billy when running normal unit tests or specs. Those libraries are used to cache the data after the first request and then on the second run all the requests are stubbed with the data were cached before.

Does anyone thought about the mechanism to stub the data while running the cypress inside the application (similarly like controlling the data state with factory bot)?

As an idea I thought to use puffing-billy as a proxy for storing the cache of the libraries are used in the application only in test environment when cypress are running. Hopefully anyone already had an experience with the described use-case.

**Comment by grantspeelman** [comment]
Would love to see a working example with VCR or puffing-billy, I think others could find something like this useful.

**Comment by elyngved** [comment]
Has anyone figured out a nice way to do this? I'm using VCR in rspec and would like to use it with Cypress too. But I don't know if there's a good way to wrap a single test in a Ruby block, or if I can use before/after hooks to "enable" and "disable" recording.

**Comment by grantspeelman** [comment]
@dmitry & @elyngved i started a discussion #106 around this issue and would like your input on this and how you currently working around this.
