### ISSUE TITLE
Generating rails coverage?

### ISSUE THREAD

**Issue by Zeouterlimits** [shakacode/cypress-on-rails#40]
Has anyone tried using Cypress (/Cypress on rails) to get coverage of rails code?
Would be nice to leverage it, if it were possible.

**Comment by dmitry** [comment]
@Zeouterlimits from the first point of view it looks simple, just place SimpleCov on the server initialization and that's it. Or I have lost something?

**Comment by Zeouterlimits** [comment]
The intricacies of SimpleCov are new to me, I'm new to rails, will take a look, thank you :)

**Comment by antarr** [comment]
Adding

```
require 'simplecov'
SimpleCov.start 'rails' do
  add_filter '/spec/'
  add_filter '/config/'
  add_filter '/vendor/'
end
```

to the top of `cypress_helper` works for me.
