### ISSUE TITLE
FactoryBot Trait not registered error

### ISSUE THREAD

**Issue by Manidavid** [shakacode/cypress-on-rails#41]
Hello everyone,
Am trying to use the existing factory bot with traits defined methods but getting Trait not registered error

Please help with document example for using multiple traits from factory bot to handle the object creation

cypress_helper.rb
```
begin
  require 'factory_bot_rails'
rescue LoadError => e
  puts e.message
  begin
    require 'factory_girl_rails'
  rescue LoadError => e
    puts e.message
  end
end

require 'cypress_on_rails/smart_factory_wrapper'

factory = CypressOnRails::SimpleRailsFactory
factory = FactoryBot if defined?(FactoryBot)
factory = FactoryGirl if defined?(FactoryGirl)

CypressOnRails::SmartFactoryWrapper.configure(
    always_reload: !Rails.configuration.cache_classes,
    factory: factory,
    files: [
      Rails.root.join('spec', 'factories.rb'),
      Rails.root.join('spec', 'factories', '**', '*.rb')
    ]
)
```

factories/users.rb
```
FactoryBot.define do
  factory :user do
    sequence(:name) { |n| "name_#{n}" }
    sequence(:email) { |n| "user_#{n}@test.com" }
    password 'Test1234'
    password_confirmation 'Test1234'

    after(:build) do |user|
      user.roles << create(:role, :everyone, user: user)
    end

    trait :admin do
      after(:build) do |user|
        user.roles << create(:role, :io_admin, user: user)
        create(:permission, :allow, :everyone, :manage, :all, :any_subject)
      end
    end
end
end
```
i want to use the admin trait for creating user

```
describe('Home Page', function() {
  beforeEach(() => {
    cy.visit('/');
    cy.appFactories([
      ['create_list', 'item', 10],
      ['create', 'field_set', { system_default: true }]  ## here also the same error when using trait but used the conditions directly here to work
     ]);
    cy.appFactories([['create', 'user', 'admin']]).then((results) => {
      cy.login(results[0].email, 'Test1234');
    });
  });
})
```

Error showing from the rails logs:

> [CY_DEV] handle_command: {"name"=>"factory_bot", "options"=>[["create", "user", "admin"]]}
> [CY_DEV] running create, ["user", "admin"]

> [CY_DEV] ArgumentError: Trait not registered: admin

**Comment by grantspeelman** [comment]
Hey @Manidavid 

Could you give some details on versions:
* Ruby
* Ruby on Rails
* FactoryBot

**Comment by Manidavid** [comment]
> Hi @grantspeelman 
> 
> Please find the details on versions:
> 
> * Ruby                   -   ruby 2.5.5p157 (2019-03-15 revision 67260)
> * Ruby on Rails     -   Rails 5.0.6
> * FactoryBot          -   factory_bot 4.8.2, factory_bot_rails 4.8.2
> * CypressonRails  -   cypress-on-rails 1.5.0

**Comment by antarr** [comment]
I'm having the same problem

**Comment by Manidavid** [comment]
@grantspeelman, any updates on this would be appropriated

**Comment by grantspeelman** [comment]
hopefully working on a fix #43

**Comment by grantspeelman** [comment]
can you please try version 1.5.1 and let me know if it fixes this

**Comment by Manidavid** [comment]
Updated cypress gem version to 1.5.1, now the factory bot traits are working great.
