### ISSUE TITLE
Unexpected change to "config/environments/test.rb"

### ISSUE THREAD

**Issue by chrislabarge** [shakacode/cypress-on-rails#45]
I was not expecting this config file to be changed upon installation.

`config.cache_classes = ENV['CI'].present?`

I think it may beneficial to mention it in the README. Upon deploying, a lot of my Rspec tests failed on CI as I did not have a ENV["CI"] variable defined.

**Comment by grantspeelman** [comment]
happy to mention it in the README.md

**Comment by grantspeelman** [comment]
https://github.com/shakacode/cypress-on-rails/commit/6ffcae768b12324fc8fadd34cea006aa0484192c
