### ISSUE TITLE
Are app fixtures and scenarios the same?

### ISSUE THREAD

**Issue by vfonic** [shakacode/cypress-on-rails#50]
I was looking at app fixtures and realized I don't see anything in there that can't be achieved through scenarios.

Why I'm thinking we could remove the app fixtures is to reduce the API size, making the gem easier to use and onboard.

There's already built-in functionality for chaining multiple scenarios:

```rb
cy.appCommands([
  { name: 'clean' },
  { name: 'scenarios/fixtures' },
  { name: 'scenarios/basic' },
])
```

We could make scenarios load/depend on each other. Maybe that would do?

Feel free to close this issue if I'm overthinking this. :)

**Comment by grantspeelman** [comment]
This first versions of cypress-on-rails came with a concept of scenarios and I wanted to create a easy transition for anyone using it. This is maybe something we can drop in version 2.
