### ISSUE TITLE
Trying to run on Semaphore CI and getting a Seg fault

### ISSUE THREAD

**Issue by jon-eckstein** [shakacode/cypress-on-rails#52]
This is a long shot, but, I'm trying to get Cypress with `cypress-on-rails` running in a CI environment.  The webserver + Cypress is running on a Linux/Ubuntu VM.  Cypress doesn't get very far, it'll get to the first time I'm creating a factory (either with scenarios or `cy.appFactories`, and will fail with a Segmentation fault described below.  Interestingly, `cy.app('clean')` doesn't cause the error. If I remove the calls to create a factory, I don't get the seg fault.
```
vendor/bundle/ruby/2.5.0/gems/cypress-on-rails-1.5.1/lib/cypress_on_rails/command_executor.rb:6: [BUG] Segmentation fault at 0x0000000000000010
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```
Any ideas?
Thanks.

**Comment by grantspeelman** [comment]
Can't help you much with Segmentation faults.
I would suggest  trying the latest ruby 2.5 version of Ruby 2.5.7
