### ISSUE TITLE
Danger, I think I found a vulnerability

### ISSUE THREAD

**Issue by michelson** [shakacode/cypress-on-rails#57]
Hi , it seems that the cypress configuration for middleware defaults to `true`
https://github.com/shakacode/cypress-on-rails/blob/master/lib/cypress_on_rails/configuration.rb#L10

I've added the configuration on the initializer but the railitie runs first, so the setting is always true !. This is a serious vulnerability.

The Railtie has to initialize the configuration on `after_initializer` , instead `initializer` this way will hook the user's configuration

```ruby
module CypressOnRails
 class Railtie < Rails::Railtie
   config.after_initialize do |app|
     if CypressOnRails.configuration.use_middleware?
         app.middleware.use Middleware
       end
    end
  end
```

**Comment by grantspeelman** [comment]
awesome, think you can create PR out of your suggestion please?

**Comment by duytd** [comment]
This is a serious issue...
