### ISSUE TITLE
Why does calling a method on a factory instance return nil?

### ISSUE THREAD

**Issue by pui** [shakacode/cypress-on-rails#63]
I'm specifically trying to get the Devise raw forgot password token to test my forgot password flow.

```
cy.appFactories([['create', 'forgot_password_user', {email: 'new-user@example.com'}]]).then((records) => {
  cy.visit(`/users/password/edit?reset_password_token=${records[0].send_reset_password_instructions}`);
});
```

`send_reset_password_instructions` returns the raw forgot password token, but when I run this code I see `/users/password/edit?reset_password_token=undefined`. Is there a way to get the return value of a method call on a factory instance?

**Comment by grantspeelman** [comment]
i think `send_reset_password_instructions` is a method call on ruby and unfortunately you cannot call ruby methods from within cypress, what gets sent back to cypress is only the attributes of the record.

**Comment by grantspeelman** [comment]
You could call the method on ruby side and return it to cypress with something like this:

```ruby
# spec/cypress/app_commands/get_reset_password_token.rb
user = FactoryBot.create('forgot_password_user', email: command_options['email'] )

# last thing in this file will be serialized and returned to cypress
{ token: user.send_reset_password_instructions }
```

then in your cypress test
```js
cy.app('get_reset_password_token', {email: 'new-user@example.com'}).then((result) => {
  cy.visit(`/users/password/edit?reset_password_token=${result.token}`);
});
```
Note: untested :smiley_cat:

**Comment by pui** [comment]
This worked. Thank you!
