### ISSUE TITLE
Traits/callbacks/sequences are not cleared for FactoryBot 6+

### ISSUE THREAD

**Issue by udovenko** [shakacode/cypress-on-rails#66]
FactoryBot has deprecated a number of top level methods in v5.1.0: https://github.com/thoughtbot/factory_bot/blob/master/NEWS.md#510-september-21-2019. Those methods include `.traits`, `.callbacks` and `.sequences`, which are used by `FactoryCleaner` module.

In FactoryBot v6.0.0 mentioned methods were removed form top namespace: https://github.com/thoughtbot/factory_bot/blob/master/NEWS.md#600-june-18-2020. As a result, `FactoryCleaner` no longer resets traits/callbacks/sequences and it leads to *Trait/... already registered* error.

Tmp workaround for this is to monkeypatch `FactoryCleaner` in your project like this:
```ruby
module CypressOnRails
  class SmartFactoryWrapper
    module FactoryCleaner
      def self.clean(factory = FactoryBot)
        factory.factories.clear
        factory::Internal.traits.clear
        factory::Internal.callbacks.clear
        factory::Internal.sequences.clear
      end
    end
  end
end
```

but of cource gem should handle this itself.

**Comment by grantspeelman** [comment]
Will look at applying this in the meantime. Also left a feature request at FactoryBot. https://github.com/thoughtbot/factory_bot/issues/1429
