### ISSUE TITLE
Closed Stream

### ISSUE THREAD

**Issue by incorvia** [shakacode/cypress-on-rails#69]
I intermittently but frequently run into an error:

```
IOError: closed stream
from /Users/me/.rbenv/versions/2.6.5/lib/ruby/2.6.0/openssl/buffering.rb:383:in `syswrite_nonblock'
```

I've tracked it down to the eval call in CommandExecutor on line 9. This is evaling a command I've provided that simply creates an object in the database using an Account.create method and shouldn't in any way cause an error like this.. I don't know if it's the server connection that is closing or a connection to the database or what.. 

Has anyone run into something frequently.. I need to restart my rails server to resolve which is annoying since I have to do it every minute or so when developing...

**Comment by grantspeelman** [comment]
Unfortunately i have not come across an error like this before.
Are you doing any file or network calls when creating an Account? Maybe worth trying to do disable those and see if the problem continues.

**Comment by grantspeelman** [comment]
@incorvia did you figure this out?
