### ISSUE TITLE
Get assertions back from the Rails app

### ISSUE THREAD

**Issue by feliperaul** [shakacode/cypress-on-rails#74]
First of all, a huge *thank you* to the maintainers of this gem. It's been transformative to use Cypress for system testing!

In some cases, I'd like to run my cypress test and then make an assertion using ruby (for instance, if a model was created, or an e-mail was fired, so on).

What would be the recommended way of accomplishing this? I know that cypress commands communicate with the rails testing server and can read return values, but before moving in this direction I'd like to know if this is actually the recommended way of accomplishing this.

If the gem already supports this, and someone can point me the way, I'll provide a pull request to improve the documentation making this clearer.

Cheers and thank you again!

**Comment by grantspeelman** [comment]
unfortunately there is currently easy/elegant way to do assertions on the rails backend.

What you could possible do is call the backend and get it to return data that you want to check and make assertions on it in cypress.

Example:

```ruby
# spec/cypress/app_commands/last_object_attributes.rb
class_name = command_options.fetch('class_name')
class_name.constantize.last&.attributes || {}
```

```js
// what an assertion could then look like in cypress
cy.app("last_object_attributes", { class_name: 'Event'} ).then((last_event) => {
     expect(last_event.name).to.equal('New Year Party')
});
```

I hope this helps 😸

**Comment by feliperaul** [comment]
@grantspeelman It helped a lot! Do you want me to issue a pull request for adding this to the documentation? I'm asking because I wouldn't change a thing (your example is perfect).

**Comment by grantspeelman** [comment]
awesome, a PR sounds good. Thank you
