### ISSUE TITLE
Cypress fails test with CSRF attack even when authenticity_token: true is in the form_for.

### ISSUE THREAD

**Issue by hamzaaltaf** [shakacode/cypress-on-rails#83]
I am stuck on this issue for almost two days now.

This is the form that I am using 
```
<%= component "modal", title: "Remove Vessel", content_only: true do |c| %>
  <% c.body do %>
    <%= form_for @vessel,
                  url: {
                    controller: controller_name,
                    action: :remove
                  },
                  builder: WrappedFormBuilder,
                  remote: true,  authenticity_token: true do |f| %>
      <div class="modal__body">
        <p>Do you want to move the users to another vessel?</p>
        </br>
        <p><b>Move Users to Vessel:</b></p>
        <%= select_tag "vessel_id", options_from_collection_for_select((Vessel.all.where.not(id: @vessel.id)), "id", "name"), include_blank: 'Do not move users' %>
      </div>
      <div class="modal__footer">
        <%= button_tag "Cancel",
                       type: :button,
                       class: "btn--link u-mr u-text-muted",
                       data: { cy: "vessel-removal-cancel", target: "form-activation.action", action: "modal#hide" } %>
        <%= f.submit "Save",
          class: "btn btn--primary",
          data: {
            cy: "vessel-submit",
            disable_with: "Removing"
          }
        %>
      </div>
    <% end %>
  <% end %>
<% end %>
```

here are the parameters that are passed to the controller.

```
<ActionController::Parameters {"utf8"=>"✓", "_method"=>"patch", "authenticity_token"=>"KF2LG9i6kRP956HbwtvaEjmy1Dq2v-slrhHWE9CrByRK7SIgx-Mk7j4KvEpRR-lBixFRM3oEhi-p8yuAs31SwQ", "vessel_id"=>"", "button"=>"", "commit"=>"Save", "controller"=>"manage/settings/vessels", "action"=>"remove", "organization_id"=>"1", "id"=>"1"} permitted: false>
```

Here is Controller Code:

```
@vessel = scope.find(params[:id])
        authorize([:manage, :settings, @vessel])

        if @vessel.move_users_and_delete(params[:vessel_id])
          redirect_to edit_manage_organization_settings_meta_data_path,
                      flash: { success: "Users Moved and Vessel updated" }
        else
          render "delete", flash: { danger: "There were issues updating the vessel" }
        end
```
Lastly this the test code.
```
it("remove an existing vessel with users", () => {
        cy.get("[data-cy=vessel-1-remove]").click();
        cy.wait(2000);
        cy.get("[data-cy=vessel-submit]").click();
        cy.wait(4000);
        cy.get("[data-cy=vessel-1]").should("not.exist");
    });
```
Cyprus shows this error.

> CypressError: Cypress detected a cross origin error happened on page load:
> 
>   > Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame.
> 
> Before the page load, you were bound to the origin policy:
>   > http://localhost:3000
> 
> A cross origin error happens when your application navigates to a new superdomain which does not match the origin policy above.
> 
> This typically happens in one of three ways:
> 
> 1. You clicked an <a> that routed you outside of your application
> 2. You submitted a form and your server redirected you outside of your application
> 3. You used a javascript redirect to a page outside of your application
> 
> Cypress does not allow you to change superdomains within a single test.
> 
> You may need to restructure some of your test code to avoid this problem.
> 
> Alternatively you can also disable Chrome Web Security which will turn off this restriction by setting { chromeWebSecurity: false } in 'cypress.json'.
> 
> https://on.cypress.io/cross-origin-violation
> 
> 
> Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'Manage > Settings > Vessels'
>

**Comment by grantspeelman** [comment]
@hamzaaltaf So sorry to here you have been struggling 😿 
I'll do my best to help you 👍🏽 

* which version of cypress are you using? have you try upgrading to the latest version already?
* What step does your test fail on?
* can you share a video of the test?
* what does the component method do?

**Comment by hamzaaltaf** [comment]
I can share for sure sir. Thanks a lot.

**Comment by justin808** [comment]
This sounds application-specific, rather than cypress-on-rails specific.

**Comment by grantspeelman** [comment]
@hamzaaltaf closing this as we have not heard from you.
