### ISSUE TITLE
getting `tail: invalid option -- 'r'` in rails server output while running cypress tests

### ISSUE THREAD

**Issue by ccrockett** [shakacode/cypress-on-rails#88]
When running cypress tests and having this gem installed on Ubuntu linux, I get the following errors in the output of the rails server when a test fails:
```
web    | tail: invalid option -- 'r'
web    | Try 'tail --help' for more information.
web    | tail: invalid option -- 'r'
web    | Try 'tail --help' for more information.
web    | tail: invalid option -- 'r'
web    | Try 'tail --help' for more information.
```

There is no `-r` option in GNU tail command that is an extension in the BSD tail command

**Comment by grantspeelman** [comment]
It would of generated a file called `cypress/app_commands/log_fail.rb`
You will see the `tail` command in there and can update it or simply comment it out.

I might comment out the `tail` by default as it's currently difficult to find a single command that will work on Mac,Windows and the various Linux variants.
