### ISSUE TITLE
Override FactoryBot association with cy.appFactories result

### ISSUE THREAD

**Issue by chasedeanda** [shakacode/cypress-on-rails#97]
In the [FactoryBot docs](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#association-overrides) they give a simple example on overriding associations by passing an existing one into the create command:
```
FactoryBot.define do
  factory :author do
    name { 'Taylor' }
  end

  factory :post do
    author
  end
end

eunji = build(:author, name: 'Eunji')
post = build(:post, author: eunji)
```

My attempt to recreate this in Cypress:
```
cy.appFactories([["build", "author", { name: "Eunji" }]]).then(
  ([author]) => {
    cy.appFactories([["build", "post", { author }]]);
  }
);
```

The command to build the post fails because `author` is returned as json and is not actually an instance of Author which throws an `Author expected, got {...} which is an instance of Hash` error in FactoryBot. Any guidance on using the results from a build command in a new `build` call?

**Comment by grantspeelman** [comment]
unfortunately you cannot access `associations` like that from Cypress.

You can either setup associations by setting the foreign key directly or by using `transient` attributes.

**Comment by grantspeelman** [comment]
Example of using foreign key

```rb
FactoryBot.define do
  factory :author do
    name { 'Taylor' }
  end

  factory :post do
    author_id { create(:author).id }
  end
end
```

then in Cypress
```js
    cy.appFactories([['create', 'author', { name: 'James' }]]).then((records) => {
     cy.appFactories([['create', 'post', { author_id: records[0].id }]])
    });
```

**Comment by grantspeelman** [comment]
Example of transient attributes (My Preferred Approach)

```rb
FactoryBot.define do
  factory :author do
    name { 'Taylor' }
  end

  factory :post do
    transient do
      author_name { 'Taylor' }
    end
    author { create(:author, name: author_name ) }
  end
end
```

then in Cypress
```js
cy.appFactories([['create', 'post', { author_name: 'James' }]]
```

**Comment by grantspeelman** [comment]
figured out a third way by using nested_atttributes 😃 

Turn these into official docs : https://github.com/shakacode/cypress-on-rails/blob/ee2fcf447ba770efe55c9dcaf908acad0cc787e1/docs/factory_bot_associations.md

Let me know if one of these ways works for you.

**Comment by chasedeanda** [comment]
@grantspeelman Awesome I appreciate your quick response and detailed examples! I like your transient attributes approach, I think we can update our factories to make that work!
